spring:
  datasource:
    dynamic:
      type: com.alibaba.druid.pool.DruidDataSource
      #druid相关配置
      druid:
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20

      primary: testdb #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        testdb:
          #基本属性
          url: jdbc:mysql://1.1.12.22:3306/testdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: 'test'
          password: 'test'
          driver-class-name: com.mysql.cj.jdbc.Driver

  #redis相关配置
  redis:
    database: 0
    host: 1.1.12.21
    port: 6379
    password: 111
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 1000
    timeout: 5000
    spring:
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

  servlet:
    multipart:
      max-request-size: 100MB

  elasticsearch:
    rest:
      uris: http://1.1.12.26:9200
      username: es
      password: es

#idea控制台默认日志级别修改
debug: true

############### mybatis-plus配置 ###############
#mybatis-plus:
#  configuration:
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

es:
  data:
    initOpen: false
    fromCount: 0
    perSize: 1000
